channels:
  - defaults
  - conda-forge

dependencies:
  - beautifulsoup4=4.12.3
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - expat=2.6.3
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - pysocks=1.7.1
  - python=3.12.5
  - readline=8.2
  - setuptools=75.1.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - urllib3=2.0.3
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - h11==0.14.0
      - idna==3.10
      - outcome==1.3.0.post0
      - requests==2.32.3
      - selenium==4.25.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - trio==0.26.2
      - trio-websocket==0.11.1
      - typing-extensions==4.12.2
      - undetected-chromedriver==3.5.5
      - websocket-client==1.8.0
      - websockets==13.1
      - wsproto==1.2.0
